dist: trusty
addons:
  chrome: stable
language: python
python:
  - "3.5"
  - "3.6"
install:
  - google-chrome --version
  - wget -N https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip && ls && rm ~/chromedriver_linux64.zip && ls && mv chromedriver ~/bin/
  - pip install -U pip
  - pip install pybuilder
  - pyb install_dependencies
  - pyb install
script:
  - echo $PATH
  - which chromedriver
  - python src/integration_tests/normal_pass_through.py
  - killall eksam-server && python src/integration_tests/incremental_adding_of_students.py
