dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install pybuilder
  - pyb install_dependencies
  - pyb install
script:
  - echo $PATH
  - which chromedriver
  - python src/integration_tests/normal_pass_through.py
  - killall eksam-server && python src/integration_tests/incremental_adding_of_students.py
