language: python
versions:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install pybuilder
  - pyb install_dependencies
  - pyb install
script:
  - python src/integration_tests/normal_pass_through.py
  - python src/integration_tests/incremental_adding_of_students.py
