#!/usr/bin/env python
"""
Usage:
    eksam-server [options] <db-location>

Options:
    --host=<HOSTNAME>, -H <HOSTNAME>
        Location of eksam server. [Default: 127.0.0.1]
    --port=<PORT>, -P <PORT>
        Port of eksam server. [Default: 5000]
    --secret=<APP_SECRET>, -s <APP_SECRET>
        Application secret for signing. [Default: EKSAM_SECRET] environment var
    --test-time=<SECONDS>, -t <SECONDS>
        Duration of the test [Default: 120]
"""

from docopt import docopt
from itsdangerous import JSONWebSignatureSerializer

from eksam import db, app

if __name__ == '__main__':
    args = docopt(__doc__)

    if args['<db-location>'] == ':memory:':
        db.bind(provider='sqlite', filename=':memory:')
    else:
        db.bind(provider='sqlite',
                filename=args['<db-location>'],
                create_db=True)

    db.generate_mapping(create_tables=True)

    app.signer = JSONWebSignatureSerializer(args['--secret'])
    app.test_time_seconds = int(args['--test-time'])

    app.run(args['--host'],
            args['--port'],
            debug=False,
            )
