#!/usr/bin/env python
"""
Usage:
    eksam-server [options] <db-location>

Options:
    --host=<HOSTNAME>, -H <HOSTNAME>
        Location of eksam server. [Default: 127.0.0.1]
    --port=<PORT>, -P <PORT>
        Port of eksam server. [Default: 5000]
    --secret=<APP_SECRET>, -s <APP_SECRET>
        Application secret for signing. [Default: EKSAM_SECRET] environment var
    --test-time=<SECONDS>, -t <SECONDS>
        Duration of the test [Default: 120]
"""

from docopt import docopt

from eksam import db, app
from eksam.wsgi import configure

if __name__ == '__main__':
    args = docopt(__doc__)

    app = configure(app, db, args)

    app.run(args['--host'],
            args['--port'],
            debug=False,
            )
